// examples/solid-vite/src/main.tsx
import { render } from 'solid-js/web';
import { Survey } from './Survey';

render(
  () => (
    <main style={{ 'max-width': '560px', margin: '3rem auto', 'font-family': 'system-ui, sans-serif' }}>
      <h1>Apex Survey — Solid example</h1>
      <Survey />
    </main>
  ),
  document.getElementById('root')!,
);

// examples/react-vite/src/main.tsx
import React from 'react';
import { createRoot } from 'react-dom/client';
import { Survey } from './Survey';

createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <main style={{ maxWidth: 560, margin: '3rem auto', fontFamily: 'system-ui, sans-serif' }}>
      <h1>Apex Survey — React example</h1>
      <Survey />
    </main>
  </React.StrictMode>,
);
