// packages/react/src/useSurveyV2Flow.ts
import { useCallback, useEffect, useMemo, useRef, useSyncExternalStore } from 'react';
import {
  createSurveyV2Engine,
  isQuestionVisible,
  type CreateSurveyV2EngineOptions,
  type EmbedEvent,
  type FlatStep,
  type PatientInfo,
  type SurveyV2Engine,
  type SurveyV2State,
  type V2DrugResult,
  type V2Question,
  type V2SubmitResult,
} from '@apextelemed/survey-core';

// ── Public surface ──────────────────────────────────────────────────────────

/**
 * Backwards-compatible outcome shape, kept in lockstep with the Solid adapter
 * so consumers can pattern-match on `outcome.kind` regardless of framework.
 * New code can read `phase` / `state` directly instead.
 */
export type SurveyV2Outcome =
  | { kind: 'loading' }
  | { kind: 'load_failed'; error: string }
  | { kind: 'questions' }
  | { kind: 'patient_info' }
  | { kind: 'submitting' }
  | { kind: 'disqualified'; drugResults: V2DrugResult[] }
  | { kind: 'complete'; result: V2SubmitResult };

export interface UseSurveyV2FlowOptions {
  /** Base URL to the Apex backend (must include the `/api` segment), or your
   *  own proxy that forwards to `/v2/embed/*`. */
  apiBaseUrl: string;
  /** Publishable key (`pk_*`) for browser-direct embeds. Omit when proxying
   *  through your own backend that injects server-side credentials. */
  publishableKey?: string;
  /** Tenant key sent as `X-Tenant-Key` when proxying through a multi-tenant
   *  backend. Ignored on browser-direct embeds. */
  tenantKey?: string;

  drugIds?: string[];
  templateId?: string;
  mode?: 'initial' | 'refill';
  /** Returning-member token (overrides drugIds/templateId/mode). */
  token?: string;

  /** Opt-in: auto-submit at the end of the questionnaire (skipping the
   *  patient-info form) when a returning/known customer's identity is complete.
   *  Default OFF. Pass with `knownPatientInfo`. See engine docs. */
  skipPatientInfoWhenComplete?: boolean;
  /** Known identity for a returning customer on the drugIds path — seeds the
   *  engine so the skip guard can pass. Resolve it BEFORE the first render (the
   *  engine is built once from the options passed at that time). */
  knownPatientInfo?: Partial<PatientInfo>;
  /** Widen the fields required for the skip (default: firstName/lastName/email/
   *  dob/state). Add any your downstream needs (e.g. shipping address). */
  requiredPatientInfoFields?: Array<keyof PatientInfo>;

  /** Override the draft storage TTL (default 24h). */
  draftTtlMs?: number;
  /** Lifecycle events from the engine. */
  onEvent?: (e: EmbedEvent) => void;
  /** Called once on a successful submission. */
  onComplete?: (result: V2SubmitResult) => void;
  /** Called on a load/submit error. */
  onError?: (error: Error) => void;
}

export interface SurveyV2Flow {
  /** Raw engine state snapshot (re-read every render via useSyncExternalStore). */
  state: SurveyV2State;
  /** Backwards-compatible discriminated union derived from `state.phase`. */
  outcome: SurveyV2Outcome;

  // Navigation
  flatSteps: FlatStep[];
  stepIndex: number;
  totalSteps: number;
  currentStep: FlatStep | null;
  visibleQuestions: V2Question[];

  // Answers
  answers: Record<string, unknown>;
  setAnswer: (questionId: string, value: unknown) => void;

  // Patient info
  patientInfo: PatientInfo;
  setPatientInfo: (patch: Partial<PatientInfo>) => void;

  // UI state
  submitting: boolean;
  validationError: string | null;

  // Actions
  next: () => Promise<void>;
  back: () => void;
  submit: () => Promise<void>;
  restart: () => void;

  /** Underlying engine — exposed for advanced use cases / tests. */
  engine: SurveyV2Engine;
}

function deriveOutcome(state: SurveyV2State): SurveyV2Outcome {
  switch (state.phase) {
    case 'loading':
      return { kind: 'loading' };
    case 'error':
      return { kind: 'load_failed', error: state.error ?? 'Unknown error' };
    case 'questions':
      return { kind: 'questions' };
    case 'patient_info':
      return { kind: 'patient_info' };
    case 'submitting':
      return { kind: 'submitting' };
    case 'disqualified':
      return { kind: 'disqualified', drugResults: state.disqualifiedResult?.drugResults ?? [] };
    case 'complete':
      return { kind: 'complete', result: state.result! };
  }
}

// ── Hook ────────────────────────────────────────────────────────────────────

/**
 * React adapter over the headless survey-v2 engine. The engine is constructed
 * once on mount from the options passed at that time — like the Solid adapter,
 * later changes to `opts` are NOT re-applied (re-mount the component, e.g. with
 * a `key`, to start a fresh survey). State is mirrored into React via
 * `useSyncExternalStore`, which re-reads the snapshot when the engine notifies.
 */
export function useSurveyV2Flow(opts: UseSurveyV2FlowOptions): SurveyV2Flow {
  // Keep the latest callbacks in a ref so the engine (built once) always calls
  // through to the current handler without forcing a rebuild.
  const handlers = useRef({ onEvent: opts.onEvent, onComplete: opts.onComplete, onError: opts.onError });
  handlers.current = { onEvent: opts.onEvent, onComplete: opts.onComplete, onError: opts.onError };

  const engineRef = useRef<SurveyV2Engine | null>(null);
  if (engineRef.current === null) {
    const engineOpts: CreateSurveyV2EngineOptions = {
      apiBaseUrl: opts.apiBaseUrl,
      publishableKey: opts.publishableKey,
      tenantKey: opts.tenantKey,
      drugIds: opts.drugIds,
      templateId: opts.templateId,
      mode: opts.mode,
      token: opts.token,
      skipPatientInfoWhenComplete: opts.skipPatientInfoWhenComplete,
      knownPatientInfo: opts.knownPatientInfo,
      requiredPatientInfoFields: opts.requiredPatientInfoFields,
      draftTtlMs: opts.draftTtlMs,
      onEvent: (e) => handlers.current.onEvent?.(e),
      onComplete: (r) => handlers.current.onComplete?.(r),
      onError: (err) => handlers.current.onError?.(err),
    };
    engineRef.current = createSurveyV2Engine(engineOpts);
  }
  const engine = engineRef.current;

  // Tear down on unmount.
  useEffect(() => {
    return () => {
      engine.destroy();
      engineRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const subscribe = useCallback((onChange: () => void) => engine.subscribe(onChange), [engine]);
  const getSnapshot = useCallback(() => engine.getState(), [engine]);
  const state = useSyncExternalStore(subscribe, getSnapshot, getSnapshot);

  const currentStep = state.flatSteps[state.stepIndex] ?? null;
  const visibleQuestions = useMemo(
    () => (currentStep ? currentStep.questions.filter((q) => isQuestionVisible(q, state.answers)) : []),
    [currentStep, state.answers],
  );

  return {
    state,
    outcome: deriveOutcome(state),
    flatSteps: state.flatSteps,
    stepIndex: state.stepIndex,
    totalSteps: state.flatSteps.length,
    currentStep,
    visibleQuestions,
    answers: state.answers,
    setAnswer: (qid, value) => engine.setAnswer(qid, value),
    patientInfo: state.patientInfo,
    setPatientInfo: (patch) => engine.setPatientInfo(patch),
    submitting: state.busy,
    validationError: state.validationError,
    next: () => engine.next(),
    back: () => engine.back(),
    submit: () => engine.submit(),
    restart: () => engine.restart(),
    engine,
  };
}

// packages/solid/src/useSurveyV2Flow.ts
import { onCleanup, onMount, type Accessor } from 'solid-js';
import { createStore, reconcile } from 'solid-js/store';
import {
  createSurveyV2Engine,
  isQuestionVisible,
  type CreateSurveyV2EngineOptions,
  type EmbedEvent,
  type FlatStep,
  type PatientInfo,
  type SurveyV2Engine,
  type SurveyV2State,
  type V2DrugResult,
  type V2Question,
  type V2SubmitResult,
} from '@apextelemed/survey-core';

// ── Public surface ──────────────────────────────────────────────────────────

/**
 * Backwards-compatible outcome shape, kept in lockstep with the React adapter
 * so consumers can pattern-match on `outcome.kind` regardless of framework.
 * New code can read `state.phase` directly instead.
 */
export type SurveyV2Outcome =
  | { kind: 'loading' }
  | { kind: 'load_failed'; error: string }
  | { kind: 'questions' }
  | { kind: 'patient_info' }
  | { kind: 'submitting' }
  | { kind: 'disqualified'; drugResults: V2DrugResult[] }
  | { kind: 'complete'; result: V2SubmitResult };

export interface UseSurveyV2FlowOptions {
  /** Base URL to the Apex backend (must include the `/api` segment), or your
   *  own proxy that forwards to `/v2/embed/*`. */
  apiBaseUrl: string;
  /** Publishable key (`pk_*`) for browser-direct embeds. Omit when proxying
   *  through your own backend that injects server-side credentials. */
  publishableKey?: string;
  /** Tenant key sent as `X-Tenant-Key` when proxying through a multi-tenant
   *  backend. Ignored on browser-direct embeds. */
  tenantKey?: string;

  drugIds?: string[];
  templateId?: string;
  mode?: 'initial' | 'refill';
  /** Returning-member token (overrides drugIds/templateId/mode). */
  token?: string;

  /** Opt-in: auto-submit at the end of the questionnaire (skipping the
   *  patient-info form) when a returning/known customer's identity is already
   *  complete. Default OFF. Pass with `knownPatientInfo`. See engine docs. */
  skipPatientInfoWhenComplete?: boolean;
  /** Known identity for a returning customer on the drugIds path — seeds the
   *  engine so the skip guard can pass. Resolve it BEFORE calling this hook
   *  (the engine is built once from the options passed at that time). */
  knownPatientInfo?: Partial<PatientInfo>;
  /** Widen the fields required for the skip to fire (default: the engine's
   *  firstName/lastName/email/dob/state). Add any your downstream needs (e.g.
   *  shipping address) so the skip never drops them. */
  requiredPatientInfoFields?: Array<keyof PatientInfo>;

  /** Override the draft storage TTL (default 24h). */
  draftTtlMs?: number;
  /** Lifecycle events from the engine. */
  onEvent?: (e: EmbedEvent) => void;
  /** Called once on a successful submission. */
  onComplete?: (result: V2SubmitResult) => void;
  /** Called on a load/submit error. */
  onError?: (error: Error) => void;
}

export interface SurveyV2Flow {
  /** Raw engine state — Solid store, fields are reactive on direct read. */
  state: SurveyV2State;

  /** Backwards-compatible discriminated union derived from `state.phase`. */
  outcome: Accessor<SurveyV2Outcome>;

  // Navigation
  flatSteps: Accessor<FlatStep[]>;
  stepIndex: Accessor<number>;
  totalSteps: Accessor<number>;
  currentStep: Accessor<FlatStep | null>;
  visibleQuestions: Accessor<V2Question[]>;

  // Answers
  answers: Accessor<Record<string, unknown>>;
  setAnswer: (questionId: string, value: unknown) => void;

  // Patient info
  patientInfo: Accessor<PatientInfo>;
  setPatientInfo: (patch: Partial<PatientInfo>) => void;

  // UI state
  submitting: Accessor<boolean>;
  validationError: Accessor<string | null>;

  // Actions
  next: () => Promise<void>;
  back: () => void;
  submit: () => Promise<void>;
  restart: () => void;

  /** Underlying engine — exposed for advanced use cases / tests. */
  engine: SurveyV2Engine;
}

// ── Hook ────────────────────────────────────────────────────────────────────

/**
 * Solid adapter over the headless survey-v2 engine. The engine is constructed
 * once when the hook runs from the options passed at that time — later changes
 * to `opts` are NOT re-applied (re-create the owning component to start a fresh
 * survey). State is mirrored into a Solid store via `reconcile()` so deep diffs
 * drive the fine-grained accessors.
 */
export function useSurveyV2Flow(opts: UseSurveyV2FlowOptions): SurveyV2Flow {
  const engineOpts: CreateSurveyV2EngineOptions = {
    apiBaseUrl: opts.apiBaseUrl,
    publishableKey: opts.publishableKey,
    tenantKey: opts.tenantKey,
    drugIds: opts.drugIds,
    templateId: opts.templateId,
    mode: opts.mode,
    token: opts.token,
    skipPatientInfoWhenComplete: opts.skipPatientInfoWhenComplete,
    knownPatientInfo: opts.knownPatientInfo,
    requiredPatientInfoFields: opts.requiredPatientInfoFields,
    draftTtlMs: opts.draftTtlMs,
    onEvent: opts.onEvent,
    onComplete: opts.onComplete,
    onError: opts.onError,
  };

  const engine = createSurveyV2Engine(engineOpts);

  // Mirror engine state into a Solid store using reconcile() so deep diffs
  // update fine-grained accessors. Subscribe immediately so the synchronous
  // load-kickoff (queueMicrotask) doesn't miss us.
  const [store, setStore] = createStore<SurveyV2State>(engine.getState());
  const unsubscribe = engine.subscribe(() => {
    setStore(reconcile(engine.getState()));
  });

  onMount(() => {
    // Re-sync once on mount in case the engine fired before the listener
    // attached (defensive; subscribe runs synchronously above so this is a no-op).
    setStore(reconcile(engine.getState()));
  });

  onCleanup(() => {
    unsubscribe();
    engine.destroy();
  });

  // Memoized accessors — Solid store deep-reactivity makes these light-weight.
  const flatSteps: Accessor<FlatStep[]> = () => store.flatSteps;
  const stepIndex: Accessor<number> = () => store.stepIndex;
  const totalSteps: Accessor<number> = () => store.flatSteps.length;
  const currentStep: Accessor<FlatStep | null> = () =>
    store.flatSteps[store.stepIndex] ?? null;
  const visibleQuestions: Accessor<V2Question[]> = () => {
    const step = currentStep();
    if (!step) return [];
    return step.questions.filter((q) => isQuestionVisible(q, store.answers));
  };
  const answers: Accessor<Record<string, unknown>> = () => store.answers;
  const patientInfo: Accessor<PatientInfo> = () => store.patientInfo;
  const submitting: Accessor<boolean> = () => store.busy;
  const validationError: Accessor<string | null> = () => store.validationError;

  const outcome: Accessor<SurveyV2Outcome> = () => {
    switch (store.phase) {
      case 'loading':
        return { kind: 'loading' };
      case 'error':
        return { kind: 'load_failed', error: store.error ?? 'Unknown error' };
      case 'questions':
        return { kind: 'questions' };
      case 'patient_info':
        return { kind: 'patient_info' };
      case 'submitting':
        return { kind: 'submitting' };
      case 'disqualified':
        return { kind: 'disqualified', drugResults: store.disqualifiedResult?.drugResults ?? [] };
      case 'complete':
        return { kind: 'complete', result: store.result! };
    }
  };

  return {
    state: store,
    outcome,
    flatSteps,
    stepIndex,
    totalSteps,
    currentStep,
    visibleQuestions,
    answers,
    setAnswer: (qid, value) => engine.setAnswer(qid, value),
    patientInfo,
    setPatientInfo: (patch) => engine.setPatientInfo(patch),
    submitting,
    validationError,
    next: () => engine.next(),
    back: () => engine.back(),
    submit: () => engine.submit(),
    restart: () => engine.restart(),
    engine,
  };
}
